### PR TITLE
Theme module

### PR DESCRIPTION
**Pull request by jcheron**
# Description

Assets manager and Themes manager (https://github.com/phpMv/ubiquity/issues/11).

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by ndL-1990** [comment]
Hi jcheron,

Six years ago I stopped working in web development. Now I got an idea and wanted to create a new project using PHP again. After a research I found some PHP frameworks and Ubiquity sounded very interesting and fast so I decided to learn it. Unfortunately, I have a few problems to understand the framework.

I followed the guide, did the quick start and wanted to use a theme "Semantic".
The installation worked fine, but since the active theme I can t add a "Special Controller" (CRUD or Auth).

So my questions are:

1. Why is this option disabled when I have an active theme (semantic) ?
2. Is it not implemented yet ?
3. Are you implementing it ?
4. If it works, what must I change to make it work ?

I found an article where the source code was listed (Some file with Admin) and saw that you disable the button when the theme is != null.

Until now I was very impressed of this framework, it's a bit hard to understand after 6 years, but I will get it in few days I think.

Thank you in advance for your help.

Kind regards,
ndL-1990

**Comment by jcheron** [comment]
Hi @ndL-1990 ,
>Why is this option disabled when I have an active theme (semantic) ?

CRUD and Auth controllers explicitly use Twig, Semantic-UI and PHPMv-UI (the RichClient library).

They were created before the Framework supported themes management.
If you only use Semantic-UI, and you don't need to switch to another theme (Bootstrap, foundation), there is no need to enable themes, and Semantic-UI is used by default.

>Is it not implemented yet ?

No, the implementation of the CRUD and Auth controllers supporting the themes would require their implementation for Bootstrap and Foundation css frameworks.

>Are you implementing it ?

For the moment, I have not yet found the time to do so: notice to contributors

**Comment by ndL-1990** [comment]
Hi @jcheron ,

Thank you for your fast reply. 
Good to know, I have already disabled the theme to continue with the guide. 

I like this framework. Unfortunately, the documentation is incomplete and I have to try a lot to get my expected results.

When I am safer on using the framework, I will write some documentation. This framework has potential and I want to support it and you where I can. 

Great job until now. 👍 

Kind regards,
ndL-1990

**Comment by jcheron** [comment]
Thanks @ndL-1990 !
You should not hesitate to contribute, even very small contributions (1 comma added, the reformulation of a sentence) contribute to the vitality and dynamism of a project.

**Pull request merged**
