### PR TITLE
master

### PR DESCRIPTION
**Pull request by Tiippex**
missing extensions in composer.json

### CODE REVIEW

**Comment by Tiippex** [comment]
I agree with PDO but you need apache when you use the getallheaders method in the PhpHttp foundation. It's an apache method.

https://github.com/phpMv/ubiquity/blob/37f83f58be9399d31e59a4b4547b794b1124b614/src/Ubiquity/utils/http/foundation/PhpHttp.php#L16

**Comment by jcheron** [comment]
The `PhpHttp` class is not used with a Swoole server. In this case, [SwooleHttp](https://github.com/phpMv/ubiquity-swoole/blob/master/src/Ubiquity/utils/http/foundation/SwooleHttp.php) from the ubiquity-swoole package takes over.
It's the same with [React or php-pm](https://github.com/phpMv/ubiquity-reactphp/blob/master/src/Ubiquity/utils/http/foundation/ReactHttp.php) servers

**Comment by Tiippex** [comment]
Oh missed that sorry.

**Comment by jcheron** [comment]
It's quite normal not to have seen it, the other classes derived from `AbstractHttp` are in external packages.

**Pull request closed without merging**
