### PR TITLE
Included initial doc from theme support

### PR DESCRIPTION
**Pull request by gildonei**
Add initial documentation about themes support, how to create a new one, folder structure and how to use a specific theme inside a controller

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jcheron** [comment]
The creation of a custom theme will be automated with the devtools (creation of the structure and files in `app/views/{newTheme}` and `public/assets/{newTheme}`)

Otherwise, we must distinguish:
- the permanent use of a theme: which requires modifying "templateEngineOptions" -> "activeTheme" in `app/config/config.php`
- and the occasional use of a theme, where we can modify the `activeTheme` at runtime, in a particular action for example with `ThemeManager :: setTheme ("custom");`

**Comment by gildonei** [comment]
I guess that only folders could be created by devtools and all asset files and view show be manually placed inside respective folders.

I think it is a common scenario, when developers buy a website template from themeforest or wrapbootstrap for sample. Those themes were shipped with all needed assets and developers need only to place they in their respective places.

The question is, when creating views using devtools, i guess devtools should have an option to ask where files will be placed, inside a theme folder or default views folder.

**Comment by jcheron** [comment]
If the theme is persistent (defined in `config.php`), then devtools can automatically create the views in the right place.
For the use of themes at runtime, we can add a `--theme=custom` parameter on the create `action` or `controller` commands

**Comment by gildonei** [comment]
I think better add a param --theme (t) is the better option, this way it also can be reused in webtools

**Comment by jcheron** [comment]
The bugs that you reported me today are logically fixed (in 9822be34d6fd3a3fd7210154207626e2971a2b1e).
- [fix] setActiveTemplate
- [fix] false values replaced with ''
- [updated] loadDefaultView for loading from `@activeTheme` 

Thank you very much for your work!

**Comment by gildonei** [comment]
I have to thankfull you for all your hard job

**Comment by jcheron** [comment]
Sometimes it's harder to get ideas than to put them into practice...

**Comment by gildonei** [comment]
Talking about ideas, what king of things and actions are logged by Monolog ?

I think that also would be useful a functionality to Audit database records and the framework should have by default a creator_id, modifier_id, created and modified.
So every insert, update, delete could be saved with it's diferencesrecording, the creator, modifier, datetime and differences from the original data to the new data making easy to find who did what on each record

A sample could be AuditStash for CakePHP - https://github.com/lorenzo/audit-stash

**Comment by jcheron** [comment]
Actually logged by Monolog:
- DAO (CRUD operations + member settings)
- Database (all operations)
- Router
- Cache (loading objects from cache + errors)
- Rest (All ops)
- Translations (loading + translations + Locale changes)
- Startup ops

It is necessary to put aside your idea in a new issue, otherwise, we will forget it ;-)

**Comment by gildonei** [comment]
I guess monolog attend all needs. With a deeper use I thik I will be able
to do better contributions.

Once enabled through webtools it starts to log all insert, update, etc?

Em ter, 19 de mar de 2019 às 16:38, jcheron <notifications@github.com>
escreveu:

**Comment by jcheron** [comment]
>Once enabled through webtools it starts to log all insert, update, etc?

yes, and you can just choose the level from which logs are emitted

**Comment by gildonei** [comment]
So I guess I did something wrong because I enabled it and all logs are always empty.
Should I activate something else?

image

**Comment by jcheron** [comment]
yes, we must add in services.php:

```\Ubiquity\log\Logger::init($config);```

I think I will add all the lines for activation services in `services.php`, in commentary and with comments

This will give everyone the opportunity to activate or not the services.

**Comment by gildonei** [comment]
OK, It works adding the line, and agree with add all services with comments
to easy enable or disable features.

Em ter, 19 de mar de 2019 às 19:53, jcheron <notifications@github.com>
escreveu:

**Comment by gildonei** [comment]
Updates on model records are not been logged, only select statements.
To log Inserts, Updates and Deletes, should I do any other config?


Em qua, 20 de mar de 2019 às 08:07, Gildonei Mendes Anacleto Junior <
gildonei.mendes@gmail.com> escreveu:

**Pull request merged**
